#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

COMMAND=/usr/bin/keystone-all
PIDFILE=/var/run/keystone/keystone.pid

depend() {
  need net
}

start() {
  ebegin "Starting ${SVCNAME}"
  start-stop-daemon --start --quiet --pidfile ${PIDFILE} --make-pidfile ${COMMAND}
  eend $?
}

stop() {
  ebegin "Stopping ${SVCNAME}"
  start-stop-daemon --stop --quiet --pidfile ${PIDFILE}
  eend $?
}
